FROM python:3

ADD modbus-sungrow-sg5d.py /solar/
ADD solarquery.py /solar/
ADD RS485Ext.py /solar/
ADD writec.so /solar/

RUN pip install pymodbus
RUN pip install dweepy
RUN pip install influxdb
RUN pip install python_dateutil
RUN pip install pytz

CMD [ "python", "./solarquery.py" ]